all: task1 task2 task3 task4 task5 task6 task7

task1: task1.cpp
	gcc task1.cpp -o task1

task2: task2.cpp
	gcc task2.cpp -o task2

task3: task3.cpp
	gcc task3.cpp -o task3

task4: task4.cpp
	gcc task4.cpp -o task4

task5: task5.cpp
	gcc task5.cpp -o task5

task6: task6.cpp
	gcc task6.cpp -o task6

task7: task7.cpp
	gcc task7.cpp -o task7



clean:
	rm -f task1 task2 task3 task4 task5 task6 task7